[package]
name = "weaver-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
bytes.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
thiserror.workspace = true
weaver-core = { path = "../weaver-core" }
